permalink: /post/:title.html
404: 404.html
paginate: 8
highlighter: pygments
mardown: kramdown
kramdown:
    input: GFM                  # use Github Flavored Markdown !important
    hard_wrap: false
    math_engine: mathjax
gems:
    - jekyll-paginate
production_url: 'https://jin-yang.github.io'
example_repository: 'https://github.com/Jin-Yang/examples/tree/master'
kernel_docs_url: 'https://www.kernel.org/doc'

description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
